[project]
name = "gpu-server-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11.11",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]
